PROJECT

Addressing:
```
WARN[0000] Config version 3-alpha has been stabilized as 3, and 3-alpha is no longer supported. Run `operator-sdk alpha config-3alpha-to-3` to upgrade your PROJECT config file to version 3
Error: error reading configuration: version 3-alpha is not supported
```

Upgrade config file from version 3-alpha to version 3

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Some clusters may have random runAsUser assignments and hence our hard-coded value may not always match with the on-cluster settings.

Do not hard-code securityContext

---

deploy/falcon-operator.yaml
deploy/parts/role.yaml

Addressing:
```
E1109 14:08:25.396770       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.6/tools/cache/reflector.go:167: Failed to watch *v1.DaemonSet: failed to list *v
1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:falcon-operator:falcon-operator" cannot list resource "daemonsets" in API group "apps" a
t the cluster scope
```

Add deamonset permissions to the operator deployed by falcon-operator

---

pkg/assets/node/daemonset.go

Addressing:
```
4s          Warning   Failed             pod/falcon-node-sensor-kqzpd   Error: configmap "falcon-node-sensor" not found
```

Daemonset: fix the name of the configmap for the daemonset

---

controllers/falcon/falconnodesensor_controller.go

Addressing the issue with the updateDeamonSetImages that would always reset the
image to falcon-node-sensor:latest.

Daemonset: allow custom image to be used

---

pkg/assets/node/daemonset.go
pkg/common/constants.go

We must not leak the permissions needed by the operator to the deamonset.
Further, falcon-operator service account is only available in the namespace
operator is running in. falcon-operator service account is not available in any
other namespace, meaning the deployment to different namespace will be assured
to fail.

Do not assign operator SA to the daemonset

---

pkg/falcon_container/falcon_registry/registry.go
pkg/falcon_container_deployer/job_pullsecret.go

Addressing:
```
2021-11-16T13:16:20.712Z        ERROR   controller-runtime.manager.controller.falconcontainer   Reconciler error        {"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer", "name": "default", "namespace": "", "error": "Cannot refresh Falcon Container image: initializing source docker
://registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor:6.31.0-1409.container.x86_64.Release.US-1: unable to retrieve auth token: invalid username/password: unknown: Authentication is required"}
```
Introduced by ed57c6a156a3573df699a826d9f135c5c937f28f.

Fix broken image push

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Addressing: OOM kill of the operator.
Broken by a25b28715d8515fd2246f3325169ef1464baddf4

Fix memory limits

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Where distroless/rootless implementation is not able to work with randomized
UIDs.
Addressing:
```
container create failed: time="2022-01-24T18:25:30Z" level=error
msg="container_linux.go:366: starting container process caused:
chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```
/cc @jhseceng

Fix broken deployment on openshift 4.7

---

pkg/falcon_container_deployer/image_push.go

This may turn out to be useful for users who deploy openshift without on-cluster registry, while they instruct operator to use that non-existent openshift on-cluster registry.

Error out explicitly when deployed on OpenShift with disabled registry

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml
deploy/falcon-operator.yaml
deploy/parts/operator.yaml

to allow easy adoption of the operator on security hardened clusters.

Operator should drop various capabilities

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml
deploy/falcon-operator.yaml
deploy/parts/operator.yaml

Interestingly, the hardening does not break the workflow on GKE, but it does break on the latest OpenShift.
Addressing: 
```
2022-02-02T10:14:14.379Z        ERROR   controller-runtime.manager.controller.falconcontainer      Reconciler error        {"reconciler group": "falcon.crowdstrik
e.com", "reconciler kind": "FalconContainer", "name": "my-setup", "namespace": "", "error": "Cannot refresh Falcon Container image: open /tmp/.dockercfg: read-onl
y file system"}
```

Revert a part of a recent hardening

---

pkg/falcon_container_deployer/job_pullsecret.go
pkg/registry/pulltoken/crowdstrike.go

It seems that this doesn't always work in some scenarios without passing the context.

Ensure context is set for pulltoken

---

docs/deployment/gke/run

Addressing:
```
$ bash -cx 'source <(curl -s https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/docs/deployment/gke/run)'
+ source /dev/fd/63
++ curl -s https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/docs/deployment/gke/run
$ (23) Failed writing body
```
@MPH13

Fix GKE depoyment script to work with broader range of shell interpreters

---

main.go

Getting namespace from the env variable is considered best practice for handling namespaces and passing them onto the controllers. These settings are also part of the RHT certification.

Add WATCH_NAMESPACE handling to main.go for cluster-scoped and single Namespace resource watching

---

main.go

Reverts CrowdStrike/falcon-operator#189
This breaks FalconContainer deployment. It forever loops in the `CONFIGURING` stage.

Revert "Add WATCH_NAMESPACE handling to main.go for cluster-scoped and single Namespace resource watching"

---

pkg/common/constants.go
pkg/falcon_container_deployer/deploy.go
pkg/falcon_container_deployer/finalizer.go
pkg/falcon_container_deployer/job.go
pkg/k8s_utils/pod_log.go

Explicitly call out container name, when fetching the logs of the pod.

Falcon Operator needs to work properly on cluster with side car products

---

controllers/falcon/falconnodesensor_controller.go

Reduces the amount of updates that happen to the ConfigMap object in the daemonset. In the future, it's possible that there might need to be additional checks if metadata changes in the configmap.

Only update daemonset configmap if the map changes

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml

- Current uid/gid settings for the controller manager break on more security conscious
kubernetes distros where uid/gid is generated off of a random uid range that might
require uid/gid to be > 65000

Remove controller-manager uid and gid settings

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml

This partly reverts e09c4abcb1723e13fab2b0a40bb6471a0b62bab6.
We have seen behaviour where the cluster that would have the operator installed previously, would never pick up the latest bits

Addressing inability to upgrade the operator

---

docs/deployment/gke/README.md

During GKE node upgrades, if nodes are stuck and you are seeing below injector errors. 
```
Internal error occurred: failed calling webhook "injector.falcon-system.svc": Post "[https://injector.falcon-system.svc:443/mutate?timeout=30s](https://urldefense.com/v3/__https://isolate.menlosecurity.com/1/3735926845/https:/injector.falcon-system.svc:443/mutate?timeout=30s__;!!K-YMnnUXXw!QQQMR38gOSOmGruWvi1MtqLmvd82wQ_UewCp2kqaeadaeWwadRNyTNX9_n4zg6NQDmnsIwB9Lbne$)": EOF
```
Explicitly label the kube-public and kube-system namespace to be not monitored by Crowdstrike. Also falcon-operator and falcon-system namespaces should be labeled to disabled. Updated the documentation with steps.

Frontdoor: Documentation for GKE node upgrade process

---

controllers/falcon/falconnodesensor_controller.go
main.go

Fixes #217
Addressing infinite loop with following error:
```
ERROR	controller.falconnodesensor	Failed to create new Configmap	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "", "DaemonSet": "/falcon-node-sensor", "Configmap.Namespace": "falcon-system", "Configmap.Name": "falcon-node-sensor-config", "error": "configmaps \"falcon-node-sensor-config\" already exists"}
```
The following events happen in the infinite loop
- Get() of the config map returns NotFound
- Create() of the config map returns AlreadyExists
For some reason, the cache of the Get command is never invalidated after
creation. We have seen this issue in EKS, but it may not be isolated to EKS.
We have not been able to reproduce this in house. …

Fix: "Failed to create new Configmap ... already exists"

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml

Removing that option from openshift marketplace.
/cc @MPH13

We cannot support deployment method confined to a single namespace

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/falcon/falconnodesensor_controller.go
deploy/falcon-operator.yaml
deploy/parts/role.yaml

DeleteAllOf, leveraged in https://github.com/CrowdStrike/falcon-operator/commit/5b8ea452d5dff81b31a8614182afbc1cb33923a3 relies upon the controller having deletecollection permissions over pods.

Add pod deletecollection permissions to operator

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml
docs/operator.md

- Allows watch_namespace to be supported in the CSV which is already enabled in main.go
- Allows customers to limit watch to a specific namespace as desired for the node sensor
- Preps for edge use-cases

Enable Single Namespace in the CSV

---

deploy/falcon-operator.yaml
deploy/parts/operator.yaml

non OLM install manifest for the manager configmap was missing a namespace definition e.g. `falcon-operator`, therefore the configmap was getting installed to the user's current kubectl context.

fix: manager configmap

---

Makefile
deploy/falcon-operator.yaml

This fixes weird errors seen in terraform templates when using deploy/falcon-operator.yaml
Addressing:
```
│ Error: API response status: Failure
│
│   with module.falcon-operator.kubernetes_manifest.test["/api/v1/namespaces/falcon-operator/serviceaccounts/falcon-operator"],
│   on .terraform/modules/falcon-operator/manifest.tf line 11, in resource "kubernetes_manifest" "test":
│   11: resource "kubernetes_manifest" "test" {
│
│ namespaces "falcon-operator" not found
```
/cc @ffalor

Changing ordering of items

---

config/manager/manager.yaml
deploy/falcon-operator.yaml
deploy/parts/operator.yaml
docs/operator.md

When kubernetes receives environment variable settings like
env:
- name: WATCH_NAMESPACE
value: ''
it will get re-written by contoller loop to
env:
- name: WATCH_NAMESPACE
value: null
This is negligable most of the time. However, when deploying from terraform, following error aborts deployment as terraform k8s provider asserts for equality post deployment.
Addressing:
```
│ Error: Provider produced inconsistent result after apply │
│ When applying changes to module.falcon-operator.kubernetes_manifest.test["/apis/apps/v1/namespaces/falcon-operator/deployments/falcon-operator-controller-manager"], │ provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.template.spec.containers[0].env[0].value: was │ cty.StringVal(""), but now …
```

Prefer null value to empty string "" when setting env variables

---

docs/deployment/gke/gcp-workload-identity.md

- default service account is not used anymore, it's `crowdstrike-falcon-sa` at stated here : https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/values.yaml#L189
- typo in the first command `gcloud projects add-iam-policy-binding`

Workload-Identity doc- fixing values and typo

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/samples/falcon_v1alpha1_falconcontainer.yaml
config/samples/falcon_v1alpha1_falconnodesensor.yaml

Add the default trace value (`none`) in the online yaml file, so it easier to ask a user to change this value.
Adding it to the default yaml for reducing troubleshooting friction.

adding default trace value in the yaml

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/samples/falcon_v1alpha1_falconcontainer-all-options.yaml
config/samples/falcon_v1alpha1_falconcontainer.yaml
config/samples/falcon_v1alpha1_falconnodesensor-all-options.yaml
config/samples/falcon_v1alpha1_falconnodesensor.yaml

Usage of `falconctlOpts` is not valid anymore.
`
Error from server (BadRequest): error when creating "falcon_v1alpha1_falconcontainer.yaml": FalconContainer in version "v1alpha1" cannot be handled as a FalconContainer: strict decoding error: unknown field "spec.injector.falconctlOpts"
`

remove falconctlOpts to use default properties

---

Makefile
deploy/falcon-operator.yaml

A following error has been registered through terraform:
```
│ Error: Forbidden attribute key in "manifest" value │
│   with module.falcon-operator.kubernetes_manifest.test["/apis/apiextensions.k8s.io/v1/customresourcedefinitions/falconcontainers.falcon.crowdstrike.com"],
│   on .terraform/modules/falcon-operator/manifest.tf line 11, in resource "kubernetes_manifest" "test":
│   11: resource "kubernetes_manifest" "test" {
│
│ 'status' attribute key is not allowed in manifest configuration
```
/cc @ffalor

Do not deploy status: subresources outside OLM

---

.github/workflows/gosec.yml

Since this rule has been removed in the gosec master branch, this will disable the rule in the scan. We can remove this when there is a new gosec release.

fix: exclude gosec rule G307 as it has been removed in the upstream branch

---

.github/workflows/release.yml
CHANGELOG.md

- Move RELEASE.md to CHANGELOG.md
- Automatically bump Makefile on release tag version bump
- Automatically create CHANGELOG
- Automatically create GH release when tag is pushed or through GUI

feat: automate releases

---

controllers/falcon_container/falconcontainer_controller.go
controllers/falcon_container/image_push.go
controllers/falcon_container/injector.go
internal/controller/common/utils.go
internal/controller/common/utils_test.go
internal/controller/image/image_refresher.go
pkg/aws/ecr.go
pkg/tls/certs.go

- Allows code re-use of TLS cert creation, checking if pods are ready before deploying, ImageFresher for registry pushing, etc. as more reconcilation types will need to be able to do the same thing.

refactor: code re-user for certs, pods ready check, ImageRefresher, etc.

---

controllers/falcon_node/falconnodesensor_controller.go

- Use semantic deepequal instead of reflect deepequal

fix: node sensor tolerations are stuck in constant update

---

bundle/manifests/falcon-operator-admission-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/falcon-operator.clusterserviceversion.yaml
bundle/manifests/falcon.crowdstrike.com_falconadmissions.yaml
bundle/manifests/falcon.crowdstrike.com_falconcontainers.yaml
bundle/metadata/annotations.yaml
config/crd/bases/falcon.crowdstrike.com_falconnodesensors.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml
controllers/admission/falconadmission_controller.go
controllers/admission/falconadmission_controller_test.go
controllers/admission/suite_test.go
controllers/falcon_container/falconcontainer_controller_test.go
controllers/falcon_container/suite_test.go
deploy/falcon-operator.yaml
internal/controller/assets/rbac_test.go
test/e2e/e2e_test.go

- Fix typos in sidecar test suite

feat: Add admission controller test suite

---

api/falcon/v1alpha1/falconnodesensor_types.go
config/crd/bases/falcon.crowdstrike.com_falconnodesensors.yaml
deploy/falcon-operator.yaml

feat(node-sensor): add infra node toleration by default

---

api/falcon/v1alpha1/falcon.go

Fixing the label of the proxy host (before : `Disable Falcon Proxy Host` => after: `Falcon Proxy Host` )
I've updated the 2 yaml files because I don't know if they were automatically generated (I can delete the additional commit if needed)

Fix label for Falcon Proxy Host

---

README.md
docs/deployment/openshift/redhat-subscription.yaml
docs/src/deployment/openshift/redhat-subscription.yaml

Tweaks discovered while writing AWS prescriptive guidance:
- Update the Subscription YAML example so it's pointing to the latest channel by default (no --edit/knowledge needed)
- Markdown link starting with `./` doesn't render to a github.com link in OperatorHub. Removing it does (see Developer Documentation link which works correctly).

Bump OpenShift Subscription example's channel to 0.9

---

cmd/main.go
version/version.go
version/version_test.go

- removes the need for logging which is unnecessary in version.go

cleanup: remove logging from version.go

---

docs/deployment/openshift/README.md
docs/src/deployment/openshift/README.md

Make the OpenShift deployment guide more opinionated to avoid common confusion and failures when deploying the sidecar sensor on OpenShift.

Clarify FalconContainer is not intended for OpenShift.

---

internal/controller/admission/falconadmission_controller.go
internal/controller/assets/deployment.go
internal/controller/assets/deployment_test.go
internal/controller/assets/validatingwebhook.go
internal/controller/assets/validatingwebhook_test.go
internal/controller/falcon_container/injector.go
pkg/tls/certs.go

- Configure new default timeout for webhook

fix(admission): always return existing tls certs on reconciliation

---

api/falcon/v1alpha1/falconcontainer_types.go
config/crd/bases/falcon.crowdstrike.com_falconcontainers.yaml
deploy/falcon-operator.yaml
docs/deployment/openshift/resources/container/README.md
docs/resources/container/README.md
docs/src/resources/container.md.tmpl
internal/controller/falcon_container/configmap.go
internal/controller/falcon_container/falconcontainer_controller.go
internal/controller/falcon_container/image_push.go
internal/controller/falcon_container/injector.go
internal/controller/falcon_container/ns.go
internal/controller/falcon_container/rbac.go
internal/controller/falcon_container/registry.go
internal/controller/falcon_container/service.go
internal/controller/falcon_container/webhook.go

- Useful for mixed EKS clusters
- Needed for certain customer workloads to be able to customize namespace.
- Prevents running a non-privileged workload next to a privileged workload

feat: allow sidecar sensor to customize namespace

---

.github/workflows/release.yml

The GitHub Actions [release workflow](https://github.com/CrowdStrike/falcon-operator/blob/main/.github/workflows/release.yml) currently runs on any tag that begins with a lowercase V, including prerelease tags. This change limits the action to full releases only.

fix: only run release workflow on full releases

---

api/falcon/v1alpha1/falcon_api.go
pkg/node/config_cache_test.go

Tests involving the Falcon API are presently limited to production endpoints. This change adds the ability to override the endpoint by setting the FALCON_API_HOST environment variable. For example:
```
$ FALCON_API_HOST=myhost.example.com make test
```

feat: allow API host override during NodeSensor config-cache tests

---

docs/deployment/gke/README.md
docs/src/templates/gkeautopilot.tmpl

Non-burstable GKE AutoPilot clusters are known to alter container resource requests and limits [under certain circumstances](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#resource-limits). If not handled correctly this can lead to crash loops and other odd behavior. This PR adds a warning to the documentation with a link to more information.

fix: add warning in docs about AutoPilot resource mismatches

---

Makefile

[RedHat's oc-mirror tool has difficulty](https://issues.redhat.com/browse/OCPBUGS-37866) with their own image registry if the images contain [provenance attestations](https://docs.docker.com/build/metadata/attestations/slsa-provenance/). Removing attestations still passes OpenShift certification, so for the time being we're doing just that. Once RedHat fixes their tooling we'll add them back in.

fix: disable provenance in Docker builds

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml

The image manifests for all applications remained the same. 
- Falcon sensor - [Manifest](https://catalog.redhat.com/software/containers/falcon-sensor/us-1/release/falcon-sensor/6508ab3efe1dc1d0132e75e8)
- Falcon container - [Manifest](https://catalog.redhat.com/software/containers/falcon-container/us-1/release/falcon-sensor/6508adb770b98c6c0c0e0561)
- Falcon image analyzer - [Manifest](https://catalog.redhat.com/software/containers/falcon-imageanalyzer/us-1/release/falcon-imageanalyzer/664cc71b9943c1297c245ad7)
- Falcon KAC - [Manifest](https://catalog.redhat.com/software/containers/falcon-kac/us-1/release/falcon-kac/651c3f5a72ff6a4b44f527be)
The new operator image has been published here: [Falcon Operator](https://catalog.redhat.com/software/containers/crowdstrike/falcon-operator/632a334 …

update image manifests for v1.2.0

---

README.md
bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml

docs: use absolute link for install guide in CSV

---

Makefile
api/falcon/v1alpha1/falconadmission_types.go
api/falcon/v1alpha1/falconcontainer_types.go
api/falcon/v1alpha1/falconimageanalyzer_types.go
api/falcon/v1alpha1/falconnodesensor_types.go
config/crd/bases/falcon.crowdstrike.com_falconadmissions.yaml
config/crd/bases/falcon.crowdstrike.com_falconcontainers.yaml
config/crd/bases/falcon.crowdstrike.com_falconimageanalyzers.yaml
config/crd/bases/falcon.crowdstrike.com_falconnodesensors.yaml
deploy/falcon-operator.yaml

- Update controller-gen to v0.14.0
- Update defaults for any field with a sub Spec

Upgrade controller-gen to v0.14.0 and fix defaults

---

test/e2e/e2e_test.go

- Flipping the order of tests to be node -> kac -> sidecar since the node cleanup pod would occasionally still be running when the sidecar would deploy.
- Updating the timeout to prevent the periodic failures caused by extended image pull times.

fix: prevent e2e test failures caused by node sensor cleanup

---

Dockerfile

Updating accommodate newly required image metadata: https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction#con-image-metadata-requirements_openshift-sw-cert-policy-container-images

Fix: Add required OpenShift image labels

---

pkg/common/common_test.go
pkg/common/funcs.go

The node cleanup DaemonSet cleans up a Falcon sensor installation in a pod init-container, with the pod container just doing a noop sleep for 10 seconds.
In clusters with a large number of nodes, it's possible that the cleanup DaemonSet runs to completion and enters CrashLoopBackOff on a particular node, before it has been deployed to all nodes.
By modifying the sleep time to infinity, the pods remain in the "Running" state instead of "CrashLoopBackOff".
See https://github.com/CrowdStrike/falcon-helm/pull/395 for more information.

Set the Falcon sensor cleanup node sleep time to infinity

---

docs/deployment/openshift/README.md
docs/src/deployment/openshift/README.md

ROSA HCP only shows worker nodes in the cluster, so we are always supported there.

docs: clarify support on ROSA Classic vs. HCP

---

config/samples/falcon_v1alpha1_falconadmission.yaml
config/samples/falcon_v1alpha1_falconcontainer-with-falcon-secret.yaml
config/samples/falcon_v1alpha1_falconcontainer.yaml
config/samples/falcon_v1alpha1_falconimageanalyzer-all-options.yaml
config/samples/falcon_v1alpha1_falconimageanalyzer.yaml
test/e2e/cr_config_test.go
test/e2e/e2e_common_test.go
test/e2e/e2e_test.go

Refactoring for readability and so that the e2e tests stop failing when the falcon-system namespace fails to delete in a timely manner.

refactor: fix e2e test namespace conflicts
