CrowdStrike/falcon-operator

PROJECT
config/manager/controller_manager_config.yaml
hack/boilerplate.go.txt
main.go

Add initial operator-sdk generated scaffolding

---

.github/workflows/go.yml
controllers/falcon/suite_test.go

At this stage we just make sure we can compile

Initial CI for falcon-operator

---

apis/falcon/v1alpha1/falconconfig_types.go
bundle/manifests/falcon.crowdstrike.com_falconconfigs.yaml
config/crd/bases/falcon.crowdstrike.com_falconconfigs.yaml

Add custom validation for Falcon Cloud region

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/falcon/falconcontainer_controller.go
pkg/falcon_container_deployer/deploy.go
pkg/falcon_container_deployer/finalizer.go
pkg/falcon_container_deployer/image_stream.go
pkg/falcon_container_deployer/job.go
pkg/k8s_utils/create.go

Finalizer (uninstall function for Falcon Container)

---

pkg/falcon_container/push_auth/credentials.go
pkg/falcon_container_deployer/image_push.go

Log the name of push secret used

---

apis/falcon/v1alpha1/falconcontainer_types.go
bundle/manifests/falcon.crowdstrike.com_falconcontainers.yaml
config/crd/bases/falcon.crowdstrike.com_falconcontainers.yaml

UX: Provide extra kubectl print column: Status & ErrorMessage

---

README.md

Adds the CrowdStrike logo and Twitter link flash.

Update README.md to add CrowdStrike logo

---

.github/workflows/go.yml

Depends on:
* https://github.com/CrowdStrike/falcon-operator/pull/70 
* https://github.com/CrowdStrike/falcon-operator/pull/71
* https://github.com/CrowdStrike/falcon-operator/pull/72

Run `make bundle` in CI to ensure it was run by the contributor

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/rbac/auth_proxy_role_binding.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role_binding.yaml

Do not add all the permissions to the default service account.

Create custom service account

---

.github/workflows/go.yml
.gitignore
Makefile
deploy/falcon-operator.yaml
deploy/parts/ns.yaml
deploy/parts/operator.yaml
deploy/parts/role.yaml
deploy/parts/role_binding.yaml
deploy/parts/service_account.yaml

Provide installation method for cluster without OLM

---

docs/deployment/gke/README.md
docs/deployment/gke/run

Amend GKE deployment to not enforce installation of OLM

---

README.md

add punctuation where missing
add articles where missing (a/an)
add code backticks for `status=DONE`
add a trailing colon to the k8s examples

Minor README Changes

---

README.md
bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/samples/falcon_v1alpha1_falconcontainer.yaml
docs/container/README.md
docs/node/README.md

documentation revamp 1/3

---

apis/falcon/v1alpha1/falcon_api.go
go.mod
go.sum

and drop the code we no longer need with the latest gofalcon

Update gofalcon dependency

---

.github/dependabot.yml

Reverts CrowdStrike/falcon-operator#139

Revert "Add dependabot config"

---

pkg/falcon_registry/node.go

Introduce registry.LastNodeTag() method

---

pkg/falcon_container/image_refresher.go
pkg/falcon_container_deployer/image_push.go
pkg/falcon_container_deployer/registry.go
pkg/registry/falcon_registry/registry.go
pkg/registry/pulltoken/crowdstrike.go
pkg/registry/pulltoken/token.go

A follow up context refactoring

---

pkg/common/funcs.go

This is what I saw just reading the code, @redhatrises. Thoughts?

Node sensor: Fix the init container creation

---

docs/deployment/gke/README.md

Update API Key pair with exact permission required - Falcon Images Download - Read.

Update API Key permission name

---

docs/container/README.md
docs/deployment/gke/gcp-workload-identity.md

/cc @gaahrdner, I would appreciate Your review.
@falcon-pioupiou, Thank You for all the hints! and I would appreciate Your review.

Document usage of GCP Workload Identity

---

controllers/falcon/falconnodesensor_controller.go
pkg/assets/secrets.go
pkg/common/funcs.go

- Use kubernetes API docker key constant
- Clean string formatting from secrets to be ui accessible

Minor Secret fixes

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/falcon/falconnodesensor_controller.go

Currently the controller errors on not being able to get some permissions to access namespaces

Make sure node controller has appropriate access to namespaces

---

config/manager/manager.yaml
main.go

Reverts CrowdStrike/falcon-operator#213

Revert "Set WATCH_NAMESPACE to cluster scope and fail on MulitNamespace InstallMode"

---

docs/deployment/gke/gcp-workload-identity.md

Fix typo in GCP service name

---

.github/workflows/go.yml

See also: https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648

Chores: CI: increase the logging detail in golangci-lint action

---

config/manager/manager.yaml
deploy/falcon-operator.yaml
deploy/parts/operator.yaml
docs/operator.md
main.go

Operator shouldn't be operating as a namespaced operator.

WIP: Make operator cluster scoped and add troubleshooting docs

---

.github/workflows/codeql.yml
.github/workflows/container_build.yml
.github/workflows/go.yml
.github/workflows/gosec.yml
.github/workflows/operator-metadata.yml

Chores: CI: run the CI also on the maintenance branches

---

README.md
bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml

- Remove Install/Uninstall steps as they create confusion and are not accurate for operatorhub, artifacthub, Red Hat Marketplace, etc. installs
- Fix some grammar

Update CSV description

---

bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manager/manager.yaml
pkg/node/config_cache.go

- Allows for use of external image registries when hosted in a store

Add ENV variable for DS image

---

controllers/falcon/falconnodesensor_controller.go
pkg/node/config_cache.go

Follow-up on https://github.com/CrowdStrike/falcon-operator/pull/250

Do not create pull token secrets when using partner enforced product image

---

.github/workflows/go.yml
controllers/falcon/suite_test.go
go.mod
go.sum
pkg/node/assets/configmap_test.go
pkg/node/assets/daemonset_test.go

tests: add node daemonset and configmap tests

---

docs/deployment/openshift/README.md

the yaml file url was not correct and generated a 404 error

Update link for FalconNodeSensor

---

deploy/falcon-operator.yaml

`kustomize cfg fmt deploy/falcon-operator.yaml`

fix: kustomize format operator non-olm deploy yaml

---

docs/developer_guide.md

- Add tool prerequisites, Deployment examples, Release instructions, etc.

feat: make developer guide more robust

---

README.md
docs/deployment/azure/README.md
docs/deployment/eks-fargate/README.md
docs/deployment/eks/README.md
docs/deployment/gke/README.md
docs/deployment/openshift/README.md
docs/install_guide.md
docs/resources/container/README.md
docs/resources/node/README.md

- make resource link better
- minor formatting fixes
- add missing settings

docs: resource docs updates

---

Makefile

- Download kustomize install script and run install as local script
- Remove kustomize install script after install is complete

fix: Makefile kustomize target

---

controllers/falcon_container/image_push.go

- Updating the version did not result in the correct sensor being deployed
- Allow image setting from env variable
- Remove versionLocking functionality as it is duplicative of additional functionality and has been shown to be confusing on what to use

fix: sensor version was not working correctly

---

README.md
docs/deployment/generic/README.md
docs/deployment/generic/falconcontainer.yaml
docs/deployment/openshift/README.md
docs/install_guide.md

- Create generic kubernetes install to make install guide more readable
- Add falconcontainer deployment yaml

feat: create generic kubernetes install

---

docs/deployment/azure/README.md
docs/deployment/azure/falconcontainer.yaml
docs/deployment/eks-fargate/README.md
docs/deployment/eks/README.md
docs/deployment/gke/README.md
docs/deployment/openshift/README.md
docs/deployment/openshift/resources/container/README.md
docs/deployment/openshift/resources/node/README.md

- Add syntax highlighting
- Fix various issues in the docs
- Update Azure falconcontainer.yaml
- Add resources to OpenShift deployment that use `oc` command

docs: doc updates

---

controllers/falcon_container/injector.go
controllers/falcon_node/falconnodesensor_controller.go
docs/deployment/openshift/resources/container/README.md
docs/deployment/openshift/resources/node/README.md
docs/resources/container/README.md
docs/resources/node/README.md
go.mod
go.sum
pkg/common/common_test.go
pkg/common/funcs.go
pkg/common/proxy.go
pkg/common/sensor_environment.go

- Operator is now proxy aware and will update sensor proxy settings based on cluster proxy configuration

feat: add proxy support

---

config/helmchart/.helmignore
config/helmchart/Chart.yaml
config/helmchart/templates/_helpers.tpl
config/helmchart/templates/operatorgroup.yaml
config/helmchart/templates/subscription.yaml
config/helmchart/values.yaml

- Operator Helm chart source code with reside in this project. This PR adds some initial Helm chart configuration to deploy the certified operator.

feat: Add initial scaffolding for helm chart source

---

Makefile

- Add variables for go flags and container build args
- Fix some grammer
- Don't run tests on build

feat: add linting to Makefile

---

cmd/main.go

feat: get args from env for OLM config

---

config/samples/falcon_v1alpha1_falconadmission.yaml
config/samples/falcon_v1alpha1_falconcontainer-all-options.yaml
config/samples/falcon_v1alpha1_falconcontainer.yaml
config/samples/falcon_v1alpha1_falconnodesensor-all-options.yaml
config/samples/falcon_v1alpha1_falconnodesensor.yaml

- Fix admission controller example
- Add missing labels to older samples

fix: config sample fixes

---

Makefile
PROJECT
api/falcon/v1alpha1/falcon.go
api/falcon/v1alpha1/falcon_api.go
config/crd/bases/falcon.crowdstrike.com_falconcontainers.yaml
config/crd/patches/cainjection_in_falconadmissions.yaml
config/crd/patches/webhook_in_falconadmissions.yaml
deploy/falcon-operator.yaml

- Fix falconadmission group api
- Add xDescriptors for falcon API and falcon settings
- Minor Makefile fixes

fix: various scaffolding fixes

---

controllers/falcon_container/falconcontainer_controller.go
controllers/falcon_container/image_stream.go
controllers/falcon_node/falconnodesensor_controller.go
internal/controller/assets/deployment.go
internal/controller/assets/deployment_test.go
internal/controller/assets/imagestream.go
internal/controller/assets/imagestream_test.go
internal/controller/assets/namespace.go
internal/controller/assets/namespace_test.go
internal/controller/assets/rbac.go
internal/controller/assets/rbac_test.go
internal/controller/common/utils.go

feat: add admission controller deployment

---

docs/deployment/azure/README.md
docs/deployment/eks-fargate/README.md
docs/deployment/eks/README.md
docs/deployment/generic/README.md
docs/deployment/gke/README.md
docs/deployment/openshift/README.md
docs/deployment/openshift/resources/container/README.md
docs/deployment/openshift/resources/node/README.md
docs/install_guide.md
docs/resources/container/README.md
docs/resources/node/README.md
docs/src/deployment/README.md.tmpl
docs/src/deployment/openshift/README.md
docs/src/resources/container.md.tmpl
docs/src/resources/node.md.tmpl
docs/src/templates/cloudshell.tmpl
docs/src/templates/presidecar.tmpl

- Remove some trailing whitespace

fix: use GH alert formatting

---

docs/deployment/openshift/resources/admission/README.md
docs/deployment/openshift/resources/container/README.md
docs/deployment/openshift/resources/node/README.md
docs/resources/admission/README.md
docs/resources/container/README.md
docs/resources/node/README.md
docs/src/resources/admission.md.tmpl
docs/src/resources/container.md.tmpl
docs/src/resources/node.md.tmpl
docs/src/templates/proxy.tmpl
pkg/node/config_cache.go

- Add node version locking
- Update proxy section in docs
- Add sensor upgrade section.

feat: update docs and add node version locking

---

cmd/main.go

feat: set operator to be permanently globally scoped

---

.github/workflows/docs.yml
.github/workflows/go.yml
.github/workflows/operator-deployment.yml
.github/workflows/operator-metadata.yml
.github/workflows/release.yml
Makefile
PROJECT
bundle.Dockerfile
bundle/manifests/falcon-operator.clusterserviceversion.yaml
bundle/manifests/falcon.crowdstrike.com_falconnodesensors.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
cmd/main.go
config/crd/kustomization.yaml
config/crd/patches/cainjection_in_falconadmissions.yaml
config/crd/patches/cainjection_in_falconcontainers.yaml
config/crd/patches/cainjection_in_falconnodesensors.yaml
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
config/manifests/kustomization.yaml
config/rbac/falconadmission_editor_role.yaml
config/rbac/falconadmission_viewer_role.yaml
config/samples/kustomization.yaml
config/scorecard/patches/basic.config.yaml
config/scorecard/patches/olm.config.yaml
docs/developer_guide.md
go.mod

feat: update to operator-sdk version 1.33.0

---

pkg/common/common_test.go
pkg/common/sensor_environment.go

Fixing #466 
I've hesitated to put a if block to check if hasPrefix but I think it's cleaner to read. thoughts ?

fixing the automatic proxy host config

---

docs/deployment/openshift/README.md
docs/src/deployment/openshift/README.md

docs: add managed OpenShift control plan/infra caveats

---

config/manifests/bases/falcon-operator.clusterserviceversion.yaml

feat: add new OpenShift feature annotations to CSV

---

pkg/registry/falcon_registry/container.go

- Return container tags that use semver

fix(iar): return IAR tags

---

docs/deployment/openshift/resources/admission/README.md
docs/deployment/openshift/resources/container/README.md
docs/resources/admission/README.md
docs/resources/container/README.md
docs/src/resources/admission.md.tmpl
docs/src/resources/container.md.tmpl

Fix Falcon container sensor readme: spec/falcon/tags must be array of string

fix sidecar readme

---

config/rbac/falconadmission_role.yaml
config/rbac/role.yaml
deploy/falcon-operator.yaml
internal/controller/admission/falconadmission_controller.go

chore(admission): sync clusterrole perms

---

config/manifests/bases/falcon-operator.clusterserviceversion.yaml

- Prep for OLMv1
- Bump OLM capability to level 2

feat: OLM updates for new versions of OLM and OpenShift

---

api/falcon/v1alpha1/falconnodesensor_funcs.go
api/falcon/v1alpha1/falconnodesensor_types.go
config/crd/bases/falcon.crowdstrike.com_falconnodesensors.yaml
deploy/falcon-operator.yaml
docs/deployment/openshift/resources/node/README.md
docs/resources/node/README.md
docs/src/resources/node.md.tmpl
internal/controller/admission/falconadmission_controller.go
internal/controller/assets/daemonset.go
internal/controller/assets/daemonset_test.go
internal/controller/common/utils.go
internal/controller/common/utils_test.go
internal/controller/falcon_node/falconnodesensor_controller.go
pkg/common/constants.go
test/e2e/e2e_test.go

- Needed for specific customer workloads

feat: allow node sensor to customize namespace

---

docs/deployment/openshift/README.md
docs/src/deployment/openshift/README.md

Improves the support stance for managed OpenShift services, based on field feedback.

docs: improve ROSA/ARO support language

---

api/falcon/v1alpha1/falconnodesensor_types.go
api/falcon/v1alpha1/zz_generated.deepcopy.go
docs/src/resources/node.md.tmpl
internal/controller/assets/daemonset.go
internal/controller/assets/daemonset_test.go
internal/controller/falcon_node/falconnodesensor_controller.go

- Update tolerations to accommodate an empty list
- Document the appending behavior of tolerations

Update tolerations to accommodate an empty list

---

internal/controller/assets/daemonset.go
internal/controller/assets/daemonset_test.go

set ClusterFirstWithHostNet, so cluster DNS resolution is possible from host network

node sensor: cdp:  set ClusterFirstWithHostNet

---

internal/controller/common/falcon_reconciler.go
pkg/falcon_secret/falcon_secret.go

Fixes [668](https://github.com/CrowdStrike/falcon-operator/issues/688)

fix: Ensure Falcon.CID matches Spec to allow for in-place updates

---

bundle/manifests/falcon-operator-image-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/falcon-operator.clusterserviceversion.yaml
config/manifests/bases/falcon-operator.clusterserviceversion.yaml
config/non-olm/patches/falcon_falconimageanalyzer_role.yaml
config/rbac/falcon_falconimageanalyzer_role.yaml
deploy/falcon-operator.yaml

Updating to match what's in helm: https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-image-analyzer/templates/cluster-role-read-access.yaml

fix: Add nodes permission to iar clusterrole
